language: python
python:
  - "3.5"
install:
  - "pip install -r requirements.txt"
script:
  - nosetests --with-coverage
branches:
  only:
  - ft-crud-api-endpoints
  - develop
  - master
after_success:
  - coveralls